---
- name: template master.yml to /usr/share/oem/coreos-install.yml
  template: src=master.yml dest=/usr/share/oem/coreos-install.yml
  when: K8S_CLUSTER_ROLE[inventory_hostname] == "master"

- name: template worker.yml to /usr/share/oem/coreos-install.yml
  template: src=worker.yml dest=/usr/share/oem/coreos-install.yml
  when: K8S_CLUSTER_ROLE[inventory_hostname] == "worker"

- name: check need ct
  raw: stat /opt/bin/ct
  register: need_ct
  ignore_errors: True    

- name: Copy ct to /opt/bin/ct 5MB
  raw: "mkdir -p /opt/bin && curl {{ HTTP_SERVER }}/ct-v0.4.2-x86_64-unknown-linux-gnu.tgz > /opt/bin/ct-v0.4.2-x86_64-unknown-linux-gnu.tgz && cd /opt/bin && tar -xzf /opt/bin/ct-v0.4.2-x86_64-unknown-linux-gnu.tgz && chmod 0744 /opt/bin/ct-v0.4.2-x86_64-unknown-linux-gnu && ln -s /opt/bin/ct-v0.4.2-x86_64-unknown-linux-gnu /opt/bin/ct" 
  when: need_ct | failed

- name: copy grub.cfg to /usr/share/oem/grub.cfg
  copy: src=grub.cfg dest=/usr/share/oem/grub.cfg mode=0600  

- name: ct /usr/share/oem/coreos-install.json
  raw: /opt/bin/ct --in-file /usr/share/oem/coreos-install.yml --out-file /usr/share/oem/coreos-install.json && chmod 0600 /usr/share/oem/coreos-install.json

- name: rm -rf /etc/machine-id
  raw: rm -rf /etc/machine-id