- name: Run kubectl.sh
  environment:
    HTTP_SERVER: '{{ HTTP_SERVER }}'
    TOOLS_KUBECTL: '{{ TOOLS_KUBECTL }}'
    REGISTRY_REMOTE: '{{ K8S_CLUSTER_REGISTRY_REMOTE }}'
    REGISTRY_REMOTE_SPLIT: '{{ K8S_CLUSTER_REGISTRY_REMOTE_SPLIT }}'
    REGISTRY_KUBECTL_REPO: '{{ K8S_IMAGES['KUBECTL']['NAME'] }}'
    REGISTRY_KUBECTL_VERSION: '{{ K8S_IMAGES['KUBECTL']['VERSION'] }}'     
  script: kubectl.sh
  when: K8S_CLUSTER_ROLE[inventory_hostname] == "master"